Web/QuizSystem.Web/Controllers/AnswerMultiSelectsController.cs
namespace QuizSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using QuizSystem.Data.Common.Repositories;
    using QuizSystem.Data.Models;
    using QuizSystem.Services.Data;
    using QuizSystem.Web.ViewModels;
    using QuizSystem.Web.ViewModels.Exams;

    public class AnswerMultiSelectsController : Controller
    {
        private readonly IAnswerMultiSelectsService answerMultiSelectsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IExamUsersService examUsersService;
        private readonly IExamsService examsService;

        public AnswerMultiSelectsController(
            IAnswerMultiSelectsService answerMultiSelectsService,
            UserManager<ApplicationUser> userManager,
            IExamUsersService examUsersService,
            IExamsService examsService)
        {
            this.answerMultiSelectsService = answerMultiSelectsService;
            this.userManager = userManager;
            this.examUsersService = examUsersService;
            this.examsService = examsService;
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> CreateAsync(string id, string examId, string answer)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var exams = this.examUsersService.Exams(user.Id);
            if (!exams.Contains(examId))
            {
                ErrorViewModelTekst model = new ErrorViewModelTekst() { Tekst = "NE ste dobaven kum izpita!" };
                return this.View("Error", model);
            }

            var exam = this.examsService.GetById<ExamViewModel>(int.Parse(examId));
            var questionFromExamIdM = exam.QuestionMultiSelects.Select(t => t.Id).ToList();
            if (exam == null || !questionFromExamIdM.Contains(int.Parse(id)) || !exam.IsOpen)
            {
                ErrorViewModelTekst model = new ErrorViewModelTekst() { Tekst = "Connot be answered!" };
                return this.View("Error", model);
            }

            await this.answerMultiSelectsService.CreateAsync(id, answer, user.Id);
            return this.RedirectToAction("ById", "Exams", new { id = examId });
        }
    }
}

Web/QuizSystem.Web/Controllers/QuestionsMultiSelectController.cs
namespace QuizSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using QuizSystem.Common;
    using QuizSystem.Data.Common.Repositories;
    using QuizSystem.Data.Models;
    using QuizSystem.Services.Data;
    using QuizSystem.Web.ViewModels.Exams;
    using QuizSystem.Web.ViewModels.QuestionsMultiCelect;

    public class QuestionsMultiSelectController : Controller
    {
        private readonly IQuestionsMultiSelectService questionsMultiSelectService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IExamUsersService examUsersService;
        private readonly IAnswerMultiSelectsService answerMultiSelectsService;
        private readonly IExamsService examsService;

        public QuestionsMultiSelectController(
            IQuestionsMultiSelectService questionsMultiSelectService,
            UserManager<ApplicationUser> userManager,
            IExamUsersService examUsersService,
            IAnswerMultiSelectsService answerMultiSelectsService,
            IExamsService examsService)
        {
            this.questionsMultiSelectService = questionsMultiSelectService;
            this.userManager = userManager;
            this.examUsersService = examUsersService;
            this.answerMultiSelectsService = answerMultiSelectsService;
            this.examsService = examsService;
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        [HttpGet]
        public IActionResult Create()
        {
            return this.View();
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        [HttpPost]
        public async Task<IActionResult> CreateAsync(QuestionMultySelectInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            var questionId = await this.questionsMultiSelectService.CreateAsync(
                model.Title,
                model.Description,
                model.AnswerTypeA,
                model.AnswerTypeB,
                model.AnswerTypeC,
                user.Id);
            return this.RedirectToAction("ById", new { id = questionId });
        }

        [Authorize]
        public async Task<IActionResult> ByIdAsync(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var exams = this.examUsersService.Exams(user.Id);
            var model = this.questionsMultiSelectService.GetById<QuestionMultiSelectOutputModel>(id);
            if (model == null)
            {
                return this.NotFound();
            }

            var answer = this.answerMultiSelectsService.Result(user.Id, model.Id);

            if (answer != null)
            {
                model.Answer = answer.Content;
            }

            if (this.User.IsInRole(GlobalConstants.ModeratorRoleName) || this.User.IsInRole(GlobalConstants.AdministratorRoleName))
            {
                return this.View(model);
            }

            if (!this.examsService.GetById<ExamViewModel>(int.Parse(model.ExamId)).IsOpen)
            {
                return this.RedirectToAction("Index", "Home");
            }

            if (!exams.Contains(model.ExamId))
            {
                return this.RedirectToAction("Index", "Home");
            }

            return this.View(model);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        public IActionResult List()
        {
            var model = this.questionsMultiSelectService.GetAll<QuestionMultiSelectOutputModel>();

            return this.View(model);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        public async Task<IActionResult> DeleteAsync(string id)
        {
            await this.questionsMultiSelectService.DeleteAsync(int.Parse(id));
            return this.RedirectToAction("LIst");
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = this.questionsMultiSelectService.GetById<QuestionMultiSelectOutputModel>(id);
            return this.View(model);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        [HttpPost]
        public async Task<IActionResult> EditAsync(QuestionMultiSelectEditModel model)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.questionsMultiSelectService.EditAsync(
                model.Title,
                model.Description,
                model.AnswerTypeA,
                model.AnswerTypeB,
                model.AnswerTypeC,
                model.Id);

            return this.RedirectToAction("ById", new { id = model.Id });
        }
    }
}

Web/QuizSystem.Web/Views/QuestionsMultiSelect/ById.cshtml
@model QuizSystem.Web.ViewModels.QuestionsMultiCelect.QuestionMultiSelectOutputModel
@using QuizSystem.Common

@{
    this.ViewData["Title"] = $"Question {Model.Title} ";
}
<h2>@this.ViewData["Title"]</h2>

@{
    <hr />
    var parms = new Dictionary<string, string>
{
                { "id", Model.Id.ToString() },
                {"ExamId",Model.ExamId }
            };
}

<div>
    <h4> @Model.Description</h4>
    @if (Model.Answer!=null)
    {
<h5>Вашият предишен избор: @Model.Answer</h5>
    }
</div>
<hr />

<form method="post" asp-controller="AnswerMultiSelects" asp-action="Create" asp-all-route-data="parms">
   
    <div>
        <ol>
            <li>
                <input type="radio" name="answer" value="@Model.AnswerTypeA" required="required" />
                <label><span style="margin-left:3px">@Model.AnswerTypeA</span></label>

            </li>
            <li>
                <input type="radio" name="answer" value="@Model.AnswerTypeB" required="required" />
                <label><span style="margin-left:3px">@Model.AnswerTypeB</span></label>

            </li>
            <li>
                <input type="radio" name="answer" value="@Model.AnswerTypeC"required="required" />
                <label><span style="margin-left:3px">@Model.AnswerTypeC</span></label>

            </li>
        </ol>

    </div>
    <hr />


    <nav class="navbar navbar-expand-sm bg-light">

        <ul class="navbar-nav">
            <li class="nav-item m=3">
                <input type="submit" class="btn btn-primary" name="Input" />
            </li>
            @if (this.User.IsInRole(GlobalConstants.ModeratorRoleName) || this.User.IsInRole(GlobalConstants.AdministratorRoleName))
            {
                <li class="nav-item m-3">
                    <a asp-action="Edit" asp-controller="QuestionsMultiSelect" asp-route-id="@Model.Id"><h5>Edit</h5></a>
                </li>
                <li class="nav-item m-3">
                    <a asp-action="Delete" asp-controller="QuestionsMultiSelect" asp-route-id="@Model.Id">Delete</a>
                </li>
            }

        </ul>

    </nav>


</form>

Web/QuizSystem.Web/Views/QuestionsMultiSelect/Create.cshtml
@model QuizSystem.Web.ViewModels.QuestionsMultiCelect.QuestionMultySelectInputModel
@{
    this.ViewData["Title"] = "Create Question";
}
<h1>@this.ViewData["Title"]</h1>
<form method="post" asp-action="Create">
    <div>

        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>

    </div>

    <div>

        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>

    </div>
    <div>

        <label asp-for="AnswerTypeA"></label>
        <textarea asp-for="AnswerTypeA" class="form-control"></textarea>
        <span asp-validation-for="AnswerTypeA" class="text-danger"></span>

    </div>
    <div>

        <label asp-for="AnswerTypeB"></label>
        <textarea asp-for="AnswerTypeB" class="form-control"></textarea>
        <span asp-validation-for="AnswerTypeB" class="text-danger"></span>

    </div>
    <div>

        <label asp-for="AnswerTypeC"></label>
        <textarea asp-for="AnswerTypeC" class="form-control"></textarea>
        <span asp-validation-for="AnswerTypeC" class="text-danger"></span>

    </div>
    <hr />
    <input type="submit" class="btn btn-primary" />

</form>

Web/QuizSystem.Web/Views/QuestionsMultiSelect/Edit.cshtml
@model QuizSystem.Web.ViewModels.QuestionsMultiCelect.QuestionMultiSelectOutputModel
@{
    this.ViewData["Title"] = "Edit Question";
}
<h1>@this.ViewData["Title"]</h1>
<form method="post" asp-action="Edit">
    <input type="hidden" name="id" value="@Model.Id" />
    <div>

        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" value="@Model.Title" />
        <span asp-validation-for="Title" class="text-danger"></span>

    </div>


    <div>

        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control">@Model.Description</textarea>
        <span asp-validation-for="Description" class="text-danger"></span>

    </div>

    <div>

    <label asp-for="AnswerTypeA"></label>
    <textarea asp-for="AnswerTypeA" class="form-control"></textarea>
    <span asp-validation-for="AnswerTypeA" class="text-danger"></span>

    </div>
    <div>

        <label asp-for="AnswerTypeB"></label>
        <textarea asp-for="AnswerTypeB" class="form-control"></textarea>
        <span asp-validation-for="AnswerTypeB" class="text-danger"></span>

    </div>
    <div>

        <label asp-for="AnswerTypeC"></label>
        <textarea asp-for="AnswerTypeC" class="form-control"></textarea>
        <span asp-validation-for="AnswerTypeC" class="text-danger"></span>

    </div>
    <hr />
    <input type="submit" class="btn btn-primary" />

</form>

Web/QuizSystem.Web/Views/QuestionsMultiSelect/List.cshtml
@model List<QuizSystem.Web.ViewModels.QuestionsMultiCelect.QuestionMultiSelectOutputModel>
<div class="row">
    @foreach (var question in Model)
    {

        <div class="col-md-4 media">

            <div class="media-body">
                <h5 class="mt-0">
                    <a asp-action="ById" asp-controller="QuestionsMultiSelect" asp-route-id="@question.Id">
                        @question.Title
                    </a>
                </h5>
                @if (question.Description.Length > 45)
                {
                    @(question.Description.Substring(0, 45) + "....")
                }
                else
                {
                    @question.Description
                }
            </div>
        </div>
    }

</div>