Web/QuizSystem.Web/Areas/Administration/Controllers/AnswerUserQuestionController.cs
namespace QuizSystem.Web.Areas.Administration.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using QuizSystem.Common;
    using QuizSystem.Data.Common.Repositories;
    using QuizSystem.Data.Models;
    using QuizSystem.Web.ViewModels.ArreasModels.ReportModels;

    [Area("Administration")]
    [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
    public class AnswerUserQuestionController : Controller
    {
        private readonly IDeletableEntityRepository<Answer> repositoryAnswers;
        private readonly IDeletableEntityRepository<Question> repositoryQuestions;
        private readonly UserManager<ApplicationUser> usermaneger;

        public AnswerUserQuestionController(
            IDeletableEntityRepository<Answer> repositoryAnswers,
            IDeletableEntityRepository<Question> repositoryQuestions,
            UserManager<ApplicationUser> usermaneger)
        {
            this.repositoryAnswers = repositoryAnswers;
            this.repositoryQuestions = repositoryQuestions;
            this.usermaneger = usermaneger;
        }

        public IActionResult ById(string id, string userId)
        {
            var question = this.repositoryQuestions.All().FirstOrDefault(t => t.Id == int.Parse(id));
            var answer = this.repositoryAnswers.All().FirstOrDefault(t => t.QuestionId == id && t.UserId == userId);
            if (answer == null)
            {
                var user = this.usermaneger.FindByIdAsync(userId);
                UserQuestionReportModel model = new UserQuestionReportModel()
                {
                    Answer = "User don not response",
                    Description = question.Description,
                    UserName = user.Result.UserName,
                    Title = question.Title,
                };
                return this.View(model);
            }
            else
            {
                var user = this.usermaneger.FindByIdAsync(userId);
                UserQuestionReportModel model = new UserQuestionReportModel()
                {
                    Answer = answer.Content,
                    Description = question.Description,
                    UserName = user.Result.UserName,
                    Title = question.Title,
                };
                return this.View(model);
            }
        }
    }
}

Web/QuizSystem.Web/Areas/Administration/Controllers/AnswerUserQuestionMultiController.cs
namespace QuizSystem.Web.Areas.Administration.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using QuizSystem.Common;
    using QuizSystem.Data.Common.Repositories;
    using QuizSystem.Data.Models;
    using QuizSystem.Web.ViewModels.ArreasModels.ReportModels;

    [Area("Administration")]
    [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
    public class AnswerUserQuestionMultiController : Controller
    {
        private readonly IDeletableEntityRepository<QuestionMultiSelect> repositoryQuestions;
        private readonly UserManager<ApplicationUser> usermaneger;
        private readonly IDeletableEntityRepository<AnswerMultiSelect> repositoryAnswersMulti;

        public AnswerUserQuestionMultiController(
            IDeletableEntityRepository<QuestionMultiSelect> repositoryQuestions,
            UserManager<ApplicationUser> usermaneger,
            IDeletableEntityRepository<AnswerMultiSelect> repositoryAnswersMulti)
        {
            this.repositoryQuestions = repositoryQuestions;
            this.usermaneger = usermaneger;
            this.repositoryAnswersMulti = repositoryAnswersMulti;
        }

        public IActionResult ById(string id, string userId)
        {
            var question = this.repositoryQuestions.All().FirstOrDefault(t => t.Id == int.Parse(id));
            var answer = this.repositoryAnswersMulti.All().FirstOrDefault(t => t.QuestionMultiSelectId == id && t.UserId == userId);
            var user = this.usermaneger.FindByIdAsync(userId);
            if (answer == null)
            {
                UserQuestionMultiReport model = new UserQuestionMultiReport()
                {
                    Answer = "User don not response",
                    Description = question.Description,
                    UserName = user.Result.UserName,
                    Title = question.Title,
                };
                return this.View(model);
            }
            else
            {
                UserQuestionMultiReport model = new UserQuestionMultiReport()
                {
                    Answer = answer.Content,
                    Description = question.Description,
                    UserName = user.Result.UserName,
                    Title = question.Title,
                };
                return this.View(model);
            }
        }
    }
}

Web/QuizSystem.Web/Areas/Administration/Controllers/DashboardController.cs
namespace QuizSystem.Web.Areas.Administration.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using QuizSystem.Common;
    using QuizSystem.Data.Common.Repositories;
    using QuizSystem.Data.Models;
    using QuizSystem.Services.Data;
    using QuizSystem.Web.Areas.ArreasModels.ReportModels;

    [Area("Administration")]
    [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
    //[Authorize(Roles = a ))]
    public class DashboardController : Controller
    {
        private readonly IUsersService usersService;
        private readonly IExamsService examsService;
        private readonly IDeletableEntityRepository<ExamUser> repository;
        private readonly UserManager<ApplicationUser> usermaneger;

        public DashboardController(
            IUsersService usersService,
            IExamsService examsService,
            IDeletableEntityRepository<ExamUser> repository,
            UserManager<ApplicationUser> usermaneger)
        {
            this.usersService = usersService;
            this.examsService = examsService;
            this.repository = repository;
            this.usermaneger = usermaneger;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        [HttpGet]
        public IActionResult UserReport()
        {
            var model = this.usersService.GetAll<Userraport>();

            return this.View(model);
        }

        public IActionResult GetAllExamsForUser(string user)
        {
            var model = new List<ExamReportModel>();

            var exams = this.repository.All().Where(t => t.UserId == user).Select(t => t.ExamId);
            model = this.examsService.GetAll<ExamReportModel>().Where(t => exams.Contains(t.Id.ToString())).ToList();
            this.ViewData["userId"] = user;
            this.ViewData["UserName"] = this.usermaneger.Users.Where(t => t.Id == user).First().UserName;
            return this.View(model);
        }

        public IActionResult GetAllExams()
        {
           var model = this.examsService.GetAll<ExamReportModel>();
           return this.View(model);
        }

        public IActionResult ByIdExam(int id)
        {
            var model = this.examsService.GetById<ExamReportModel>(id);

            model.Users = this.repository.All().Where(h => h.ExamId == id.ToString()).Select(b => b.User.UserName);

            return this.View(model);
        }

        public IActionResult ByIdExamUser(int id, string userId)
        {
            this.ViewData["userId"] = userId;
            this.ViewData["UserName"] = this.usermaneger.Users.Where(t => t.Id == userId).First().UserName;
            var model = this.examsService.GetById<ExamReportModel>(id);
            return this.View(model);
        }
    }
}

Web/QuizSystem.Web/Areas/Administration/Views/Dashboard/ByIdExam.cshtml
@model QuizSystem.Web.Areas.ArreasModels.ReportModels.ExamReportModel
@{
    this.ViewData["Title"] = Model.Name;
}
@if (Model.IsOpen)
{
    this.ViewData["Condition"] = "- Open";
}
else
{
    this.ViewData["Condition"] = "- Closed";
}
<h4 class="display-4">@Model.Name @this.ViewData["Condition"]</h4>
<div class="card">
    <div class="card-header">
        @Model.Description
    </div>
    <div class="card-body">
      
      
       <h6>Допуснати погребители до изпита</h6>
        <hr />
            @foreach (var item in Model.Users)
            {
                <p>@item</p>
            }


    </div>
    <dv class="card-footer">


    </dv>

</div>

Web/QuizSystem.Web/Areas/Administration/Views/Dashboard/ByIdExamUser.cshtml
@model QuizSystem.Web.Areas.ArreasModels.ReportModels.ExamReportModel
@{
    this.ViewData["Title"] = Model.Name;
}
@if (Model.IsOpen)
{
    this.ViewData["Condition"] = "- Open";
}
else
{
    this.ViewData["Condition"] = "- Closed";
}
<h5 class="display-6">@Model.Name @this.ViewData["Condition"] report for @this.ViewData["UserName"]</h5>
<div class="card">
    <div class="card-header alert-info">
        @Model.Description
    </div>
    <div class="card-body">


        @foreach (var item in Model.Questions)
        {
            var parem = new Dictionary<string, string>() {
                {"id",item.Id.ToString()},
                {"userId",this.ViewData["userId"].ToString() }
            };

            {
                <h4 class="media-heading"><a asp-controller="AnswerUserQuestion" asp-action="ById" asp-all-route-data="parem">@item.Title</a></h4>
            }
        }
        @foreach (var item in Model.QuestionMultiSelects)
        {
            var parem = new Dictionary<string, string>() {
                {"id",item.Id.ToString()},
                {"userId",this.ViewData["userId"].ToString() }
            };
            <h4 class="media-heading"><a asp-controller="AnswerUserQuestionMulti" asp-action="ById" asp-all-route-data="parem">@item.Title</a></h4>
        }



    </div>
    <dv class="card-footer">


    </dv>

</div>

Web/QuizSystem.Web/Areas/Administration/Views/Dashboard/GetAllExams.cshtml
@model List<QuizSystem.Web.Areas.ArreasModels.ReportModels.ExamReportModel>
@{
    this.ViewData["Title"] = "Choose exam for report";
}
    <div class="row">
        @foreach (var exam in Model)
        {
            var parm = new Dictionary<string, string>
            {
                {"id",exam.Id.ToString() },
                  

            };
            <div class="col-md-4 media">

                <div class="media-body">
                    <h5 class="mt-0">
                        <a asp-area="Administration" asp-action="ByIdExam" asp-controller="Dashboard" asp-all-route-data="@parm">
                            @exam.Name
                        </a>
                    </h5>
                    @exam.Description
                </div>
            </div>
        }

    </div>

Web/QuizSystem.Web/Areas/Administration/Views/Dashboard/GetAllExamsForUser.cshtml
@model List<QuizSystem.Web.Areas.ArreasModels.ReportModels.ExamReportModel>
@{
    this.ViewData["Title"] = "Choose exam for report";
}
<h4>Exams from @this.ViewData["Username"]</h4>
<div class="row">
    @foreach (var exam in Model)
    {
        var parm = new Dictionary<string, string>
    {
                {"id",exam.Id.ToString() },
                   {"userid",this.ViewData["userId"].ToString() }

            };
        <div class="col-md-4 media">

            <div class="media-body">
                <h5 class="mt-0">
                    <a asp-action="ByIdExamUser" asp-controller="Dashboard" asp-all-route-data="@parm">
                        @exam.Name
                    </a>
                </h5>
                @exam.Description
            </div>
        </div>
    }

</div>

Web/QuizSystem.Web/Areas/Administration/Views/Dashboard/Index.cshtml
@model QuizSystem.Web.ViewModels.Administration.Dashboard.IndexViewModel
@{
    this.ViewData["Title"] = "Admin dashboard";
}

<h1>@this.ViewData["Title"]</h1>

<div class="container">
    <div class="row">
        <div class="col-sm-6 bg-success">
            <nav class="navbar bg-light">

                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a asp-area="Administration" asp-controller="Administration" asp-action="CreateRole">Create Role</a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="Administration" asp-controller="Administration" asp-action="ChooseaRole">Choosea Role and remove or add user for role</a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="col-sm-6 bg-warning">
            <nav class="navbar bg-light">

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a asp-area="Administration" asp-controller="Dashboard" asp-action="UserReport">User Report</a>
                </li>
                <li class="nav-item">
                    <a asp-area="Administration" asp-controller="Dashboard" asp-action="GetAllExams">Exam Report</a>
                </li>
            </ul>
            </nav>
        </div>
    </div>
</div>

Web/QuizSystem.Web/Areas/Administration/Views/Dashboard/UserReport.cshtml
@model List<QuizSystem.Web.Areas.ArreasModels.ReportModels.Userraport>
@{
    this.ViewData["Title"] = "Choose user for report";
}
    <form method="post" asp-action="GetAllExamsForUser" asp-controller="Dashboard" asp-area="Administration">
        <div class="card">
            <div class="card-header"><h3>@this.ViewData["Title"]</h3></div>
            <div class="card-body">


                @foreach (var item in Model)

                {

                    <div>
                        <input type="radio" name="user" value="@item.Id" />
                        <label><span style="margin-left:3px">@item.UserName</span></label>
                    </div>
                }

            </div>
            <div class="card-footer">
                <input type="submit" class="btn btn-primary" name="input"/>
            </div> 
        </div>
    </form>