Web/QuizSystem.Web/Controllers/AnswersController.cs
namespace QuizSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using QuizSystem.Data.Common.Repositories;
    using QuizSystem.Data.Models;
    using QuizSystem.Services.Data;
    using QuizSystem.Web.ViewModels;
    using QuizSystem.Web.ViewModels.Exams;

    public class AnswersController : Controller
    {
        private readonly IAnswersSerrvice answersService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IExamUsersService examUsersService;
        private readonly IExamsService examsService;

        public AnswersController(
            IAnswersSerrvice answersService,
            UserManager<ApplicationUser> userManager,
            IExamUsersService examUsersService,
            IExamsService examsService)
        {
            this.answersService = answersService;
            this.userManager = userManager;
            this.examUsersService = examUsersService;
            this.examsService = examsService;
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync(string id, string examId, string answer)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var exams = this.examUsersService.Exams(user.Id);
            if (!exams.Contains(examId))
            {
                ErrorViewModelTekst model = new ErrorViewModelTekst() { Tekst = "NE ste dobaven kum izpita!" };
                return this.View("Error", model);
            }

            var exam = this.examsService.GetById<ExamViewModel>(int.Parse(examId));
            var questionFromExamId = exam.Questions.Select(t => t.Id).ToList();

            if (exam == null || !questionFromExamId.Contains(int.Parse(id)) || !exam.IsOpen)
            {
                ErrorViewModelTekst model = new ErrorViewModelTekst() { Tekst = "Connot be answered!!" };
                return this.View("Error", model);
            }

            await this.answersService.CreateAsync(id, answer, user.Id);
            return this.RedirectToAction("ById", "Exams", new { id = examId });
        }
    }
}

Web/QuizSystem.Web/Controllers/QuestionsController.cs
namespace QuizSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using QuizSystem.Common;
    using QuizSystem.Data.Common.Repositories;
    using QuizSystem.Data.Models;
    using QuizSystem.Services.Data;
    using QuizSystem.Web.ViewModels.Exams;
    using QuizSystem.Web.ViewModels.Questions;

    public class QuestionsController : Controller
    {
        private readonly IQuestionsService questionsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IExamUsersService examUsersService;
        private readonly IAnswersSerrvice answersSerrvice;
        private readonly IExamsService examsService;

        public QuestionsController(
            IQuestionsService questionsService,
            UserManager<ApplicationUser> userManager,
            IExamUsersService examUsersService,
            IAnswersSerrvice answersSerrvice,
            IExamsService examsService)
        {
            this.questionsService = questionsService;
            this.userManager = userManager;
            this.examUsersService = examUsersService;
            this.answersSerrvice = answersSerrvice;
            this.examsService = examsService;
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        [HttpGet]
        public IActionResult Create()
        {
            return this.View();
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        [HttpPost]
        public async Task<IActionResult> CreateAsync(QuestionInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            var questionId = await this.questionsService.CreateAsync(model.Title, model.Description, user.Id);

            return this.RedirectToAction("ById", new { id= questionId });
        }

        [Authorize]
        public async Task<IActionResult> ByIdAsync(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var exams = this.examUsersService.Exams(user.Id);
            var model = this.questionsService.GetById<QuestionsViewOutputModel>(id);

            if (model == null)
            {
                return this.NotFound();
            }

            var answer = this.answersSerrvice.Result(user.Id, model.Id);
            if (answer != null)
            {
                model.Answer = answer.Content;
            }

            if (this.User.IsInRole(GlobalConstants.AdministratorRoleName) || this.User.IsInRole(GlobalConstants.ModeratorRoleName))
            {
                return this.View(model);
            }

            if (!this.examsService.GetById<ExamViewModel>(int.Parse(model.ExamId)).IsOpen)
            {
                return this.RedirectToAction("Index", "Home");
            }

            if (!exams.Contains(model.ExamId))
            {
                return this.RedirectToAction("Index", "Home");
            }

            return this.View(model);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = this.questionsService.GetById<QuestionsViewOutputModel>(id);
            return this.View(model);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        [HttpPost]
        public async Task<IActionResult> EditAsync(QoesttionEditModel model)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.questionsService.EditAsync(model.Title, model.Description, model.Id);

            return this.RedirectToAction("ById", "Questions", new { id = model.Id });
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        public async Task<IActionResult> DeleteAsync(string id)
        {
            await this.questionsService.DeleteAsync(int.Parse(id));
            return this.RedirectToAction("List", "Questions");
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        public IActionResult List()
        {
            var model = this.questionsService.GetAll<QuestionsViewOutputModel>();

            return this.View(model);
        }
    }
}

Web/QuizSystem.Web/Views/Questions/ById.cshtml
@model QuizSystem.Web.ViewModels.Questions.QuestionsViewOutputModel
@using QuizSystem.Common

@{
    this.ViewData["Title"] = $"Question {Model.Title} ";
}
<h2>@this.ViewData["Title"]</h2>

@{
    var parms = new Dictionary<string, string>
{
                { "id", Model.Id.ToString() },
                {"ExamId",Model.ExamId }
            };
}

<div>
    <h4> @Model.Description</h4>
</div>
<form method="post" asp-controller="Answers" asp-action="Create" asp-all-route-data="parms">

    <div>

        <label asp-for="Answer"></label>
        <input asp-for="Answer" class="form-control" />
        <span asp-validation-for="Answer" class="text-danger"></span>

    </div>
    <hr />
    
    <nav class="navbar navbar-expand-sm bg-light">
        <ul class="navbar-nav">
            <li class="nav-item m-3">
                <input type="submit" class="btn btn-primary " />
            </li>
            @if (this.User.IsInRole(GlobalConstants.ModeratorRoleName) || this.User.IsInRole(GlobalConstants.AdministratorRoleName))
            {
                <li class="nav-item m-3">
                    <a asp-action="Edit" asp-controller="Questions" asp-route-id="@Model.Id"><h5>Edit</h5></a>
                </li>
                <li class="nav-item m-3">
                    <a asp-action="Delete" asp-controller="Questions" asp-route-id="@Model.Id">Delete</a>
                </li>
            }

        </ul>

    </nav>
</form>

Web/QuizSystem.Web/Views/Questions/Create.cshtml
@model QuizSystem.Web.ViewModels.Questions.QuestionInputModel
@{ 
    this.ViewData["Title"] = "Create Question";
}
    <h1>@this.ViewData["Title"]</h1>
    <form method="post" asp-action="Create">
        <div>

            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>

        </div>


        <div >

            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>

        </div>
        <hr />
        <input type="submit" class="btn btn-primary" />

    </form>

Web/QuizSystem.Web/Views/Questions/Edit.cshtml
@model QuizSystem.Web.ViewModels.Questions.QuestionsViewOutputModel
@{
    this.ViewData["Title"] = "Edit Question";
}
<h1>@this.ViewData["Title"]</h1>
<form method="post" asp-action="Edit" >
    <input type="hidden" name="id" value="@Model.Id" />
    <div>

        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" value="@Model.Title" />
        <span asp-validation-for="Title" class="text-danger"></span>

    </div>


    <div>

        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control">@Model.Description</textarea>
        <span asp-validation-for="Description" class="text-danger"></span>

    </div>
    <hr />
    <input type="submit" class="btn btn-primary" />

</form>

Web/QuizSystem.Web/Views/Questions/List.cshtml
@model List<QuizSystem.Web.ViewModels.Questions.QuestionsViewOutputModel>
    <div class="row">
        @foreach (var question  in Model)
        {

            <div class="col-md-4 media">

                <div class="media-body">
                    <h5 class="mt-0">
                        <a asp-action="ById" asp-controller="Questions" asp-route-id="@question.Id">
                            @question.Title
                        </a>
                    </h5>
                    @if (question.Description.Length > 45)
                    {
                        @(question.Description.Substring(0, 45) + "....")
                    }
                    else
                    {
                      @question.Description
                    }

                </div>
            </div>
        }

    </div>