Web/QuizSystem.Web/Controllers/ExamUsersController.cs
namespace QuizSystem.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using QuizSystem.Common;
    using QuizSystem.Services.Data;
    using QuizSystem.Web.ViewModels.ExamUses;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
    public class ExamUsersController : Controller
    {
        private readonly IUsersService usersService;
        private readonly IExamUsersService examUsersService;

        public ExamUsersController(IUsersService usersService, IExamUsersService examUsersService)
        {
            this.usersService = usersService;
            this.examUsersService = examUsersService;
        }

        [Authorize]
        [HttpGet]
        public IActionResult AddUsersToExam(int id)
        {
            var model = new ExamUsersview() { examUsers = this.usersService.GetAll<ExamUserView>(), ExamId = id };
            return this.View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddUsersToExamAsync(string[] username, string idexam)
        {
           await this.examUsersService.AddUserToExamAsync(int.Parse(idexam), username);

           return this.RedirectToAction("Index", "Home");
        }
    }
}

Web/QuizSystem.Web/Controllers/ExamsController.cs
namespace QuizSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using QuizSystem.Common;
    using QuizSystem.Data.Common.Repositories;
    using QuizSystem.Data.Models;
    using QuizSystem.Services.Data;
    using QuizSystem.Web.ViewModels;
    using QuizSystem.Web.ViewModels.Exams;

    public class ExamsController : Controller
    {
        private readonly IExamsService examsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IExamUsersService examUsersService;

        public ExamsController(
            IExamsService examsService,
            UserManager<ApplicationUser> userManager,
            IExamUsersService examUsersService)
        {
            this.examsService = examsService;
            this.userManager = userManager;
            this.examUsersService = examUsersService;
        }

        [HttpGet]
        [Authorize(Roles =GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        public async Task<IActionResult> CreateAsync(string name, string description)
        {
            if (!this.examsService.CheckForQuestions())
            {
                ErrorViewModelTekst model = new ErrorViewModelTekst() { Tekst = "Няма свободни въпроси със отворен отговор, създайте нови въпроси. " };
                return this.View("Error", model);
            }

            if (!this.examsService.CheckForQuestionsMulti())
            {
                ErrorViewModelTekst model = new ErrorViewModelTekst() { Tekst = "Няма свободни въпроси с отговор с избор, създайте нови въпроси. " };
                return this.View("Error", model);
            }

            var examId = await this.examsService.CreateAsync(name, description);
            return this.RedirectToAction("ById", new { id = examId });
        }

        [Authorize]
        public async Task<IActionResult> ByIdAsync(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            this.ViewData["userId"] = user.Id;
            var exams = this.examUsersService.Exams(user.Id);
            var model = this.examsService.GetById<ExamViewModel>(id);
            if (model == null)
            {
                return this.NotFound();
            }

            if (this.User.IsInRole(GlobalConstants.AdministratorRoleName) || this.User.IsInRole(GlobalConstants.ModeratorRoleName))
            {
                return this.View(model);
            }
            else

            if (!exams.Contains(model.Id.ToString()) || !model.IsOpen)
            {
                return this.RedirectToAction("Index", "Home");
            }

            return this.View(model);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        public async Task<IActionResult> DeleteExamAsync(string id)
        {
          await this.examsService.DeleteAsync(int.Parse(id));

          return this.RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        public async Task<IActionResult> OpenOrCloseExamAsync(string id)
        {
            await this.examsService.OpenorNotOpen(int.Parse(id));
            return this.RedirectToAction("ById", new { id = int.Parse(id) });
        }
    }
}

Web/QuizSystem.Web/Controllers/QuestionsMultiSelectController.cs
namespace QuizSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using QuizSystem.Common;
    using QuizSystem.Data.Common.Repositories;
    using QuizSystem.Data.Models;
    using QuizSystem.Services.Data;
    using QuizSystem.Web.ViewModels.Exams;
    using QuizSystem.Web.ViewModels.QuestionsMultiCelect;

    public class QuestionsMultiSelectController : Controller
    {
        private readonly IQuestionsMultiSelectService questionsMultiSelectService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IExamUsersService examUsersService;
        private readonly IAnswerMultiSelectsService answerMultiSelectsService;
        private readonly IExamsService examsService;

        public QuestionsMultiSelectController(
            IQuestionsMultiSelectService questionsMultiSelectService,
            UserManager<ApplicationUser> userManager,
            IExamUsersService examUsersService,
            IAnswerMultiSelectsService answerMultiSelectsService,
            IExamsService examsService)
        {
            this.questionsMultiSelectService = questionsMultiSelectService;
            this.userManager = userManager;
            this.examUsersService = examUsersService;
            this.answerMultiSelectsService = answerMultiSelectsService;
            this.examsService = examsService;
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        [HttpGet]
        public IActionResult Create()
        {
            return this.View();
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        [HttpPost]
        public async Task<IActionResult> CreateAsync(QuestionMultySelectInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            var questionId = await this.questionsMultiSelectService.CreateAsync(
                model.Title,
                model.Description,
                model.AnswerTypeA,
                model.AnswerTypeB,
                model.AnswerTypeC,
                user.Id);
            return this.RedirectToAction("ById", new { id = questionId });
        }

        [Authorize]
        public async Task<IActionResult> ByIdAsync(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var exams = this.examUsersService.Exams(user.Id);
            var model = this.questionsMultiSelectService.GetById<QuestionMultiSelectOutputModel>(id);
            if (model == null)
            {
                return this.NotFound();
            }

            var answer = this.answerMultiSelectsService.Result(user.Id, model.Id);

            if (answer != null)
            {
                model.Answer = answer.Content;
            }

            if (this.User.IsInRole(GlobalConstants.ModeratorRoleName) || this.User.IsInRole(GlobalConstants.AdministratorRoleName))
            {
                return this.View(model);
            }

            if (!this.examsService.GetById<ExamViewModel>(int.Parse(model.ExamId)).IsOpen)
            {
                return this.RedirectToAction("Index", "Home");
            }

            if (!exams.Contains(model.ExamId))
            {
                return this.RedirectToAction("Index", "Home");
            }

            return this.View(model);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        public IActionResult List()
        {
            var model = this.questionsMultiSelectService.GetAll<QuestionMultiSelectOutputModel>();

            return this.View(model);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        public async Task<IActionResult> DeleteAsync(string id)
        {
            await this.questionsMultiSelectService.DeleteAsync(int.Parse(id));
            return this.RedirectToAction("LIst");
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = this.questionsMultiSelectService.GetById<QuestionMultiSelectOutputModel>(id);
            return this.View(model);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.ModeratorRoleName)]
        [HttpPost]
        public async Task<IActionResult> EditAsync(QuestionMultiSelectEditModel model)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.questionsMultiSelectService.EditAsync(
                model.Title,
                model.Description,
                model.AnswerTypeA,
                model.AnswerTypeB,
                model.AnswerTypeC,
                model.Id);

            return this.RedirectToAction("ById", new { id = model.Id });
        }
    }
}

Web/QuizSystem.Web/Views/Exams/ById.cshtml
@model QuizSystem.Web.ViewModels.Exams.ExamViewModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@using QuizSystem.Data.Models
@using Microsoft.AspNetCore.Identity
@using QuizSystem.Common
@using QuizSystem.Services.Data
@inject IAnswerMultiSelectsService service
@inject IAnswersSerrvice serviceTwo
@{
    this.ViewData["Title"] = Model.Name;
}
@if (this.User.IsInRole(GlobalConstants.ModeratorRoleName) || this.User.IsInRole(GlobalConstants.AdministratorRoleName))
{
    if (Model.IsOpen)
    {
        this.ViewData["Condition"] = "- Open";
    }
    else
    {
        this.ViewData["Condition"] = "- Closed";
    }
}
else { this.ViewData["Condition"] = ""; }

<h7 class="display-4">@Model.Name @this.ViewData["Condition"]</h7>

<div class="card">
    <div class="card-header alert-info">
        @Model.Description
    </div>
    <div class="card-body">
        <ol >
           
            @foreach (var item in Model.Questions)
            {
             
                <li>
                    @if (serviceTwo.Result(this.ViewData["userId"].ToString(), item.Id) == null)
                    {
                        <h4 class="media-heading"><a asp-controller="Questions" asp-action="ById" asp-route-id="@item.Id" class="text-success">@item.Title</a></h4>
                    }
                    else
                    {
                        <h4 class="media-heading"><a asp-controller="Questions" asp-action="ById" asp-route-id="@item.Id" class="text-primary">@item.Title</a></h4>
                    }

                </li>

            }

            @foreach (var item in Model.QuestionMultiSelects)

            {
                <li>
                    @if (service.Result(this.ViewData["userId"].ToString(), item.Id) == null)
                    {
                        <h4 class="media-heading"><a asp-controller="QuestionsMultiSelect" asp-action="ById" asp-route-id="@item.Id" class="text-success">@item.Title</a></h4>
                    }
                    else
                    {
                        <h4 class="media-heading"><a asp-controller="QuestionsMultiSelect" asp-action="ById" asp-route-id="@item.Id" class="text-primary">@item.Title</a></h4>
                    }


                </li>

            }

        </ol>

    </div>
    <div class="card-footer">
        @{

            var parms = new Dictionary<string, string>
            {
                { "id", Model.Id.ToString() },

            };
        }

        <nav class="navbar navbar-expand-sm bg-light">


            @if (this.User.IsInRole(GlobalConstants.ModeratorRoleName) || this.User.IsInRole(GlobalConstants.AdministratorRoleName))
            {
            <ul class="navbar-nav ">
                <li class="nav-item m-3">
                    <h4><a asp-controller="ExamUsers" asp-action="AddUsersToExam" asp-all-route-data="parms">Add user to exam</a></h4>
                </li>

                <li class="nav-item m-3 ">
                    <h4><a asp-controller="Exams" asp-action="DeleteExam" asp-all-route-data="parms">Delete exam</a></h4>

                </li>
                <li class="nav-item m-3 ">
                    <h4><a asp-controller="Exams" asp-action="OpenOrCloseExam" asp-all-route-data="parms">Change status Exam</a></h4>

                </li>
               
            </ul>

            }
        </nav>

    </div>



</div>

Web/QuizSystem.Web/Views/Exams/Create.cshtml
@model QuizSystem.Web.ViewModels.Exams.ExamInputModel
@{
    this.ViewData["Title"] = "Create Exam";
}
<h1>@this.ViewData["Title"]</h1>
<form method="post" asp-action="Create">
    <div>

        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>

    </div>


    <div>

        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>

    </div>
    <hr />
    <input type="submit" class="btn btn-primary" />

</form>